;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-intermediate-lambda-reader.ss" "lang")((modname 20-29) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #t)))
;;
;; **************************
;;   Project Euler
;; **************************
;;

;; ==== Question 20 ========================


;; (factorial nat) produces the factorial of a nat.
;; factorial: Nat -> Nat

(define (factorial nat)
  (foldr * 1 (build-list nat add1)))


;; (digit-sum nat) produces the sum of the digits of a nat.
;; digit-sum: Nat -> Nat

(define (digit-sum nat)
  (foldr + 0 (map string->number (explode (number->string nat)))))


;(digit-sum (factorial 100))


;; ==== Question 21 ========================


;; (factor-sum nat) produces the sum of positive proper divisors of the natural
;;   number.
;; factor-sum: Nat -> Nat

(define (factor-sum nat)
  (local [(define cap (sqrt nat))
          (define perf-sqr? (= cap (floor cap)))
          (define (next-factor current sum)
            (cond [(and (> current cap) perf-sqr?) (- sum nat cap)]
                  [(> current cap) (- sum nat)]
                  [(zero? (remainder nat current))
                   (next-factor (add1 current) (+ sum current (/ nat current)))]
                  [else
                   (next-factor (add1 current) sum)]))]
    (next-factor 1 0)))


;; (sum-amicable-numbers number-dict) produces the sum of all amicable numbers
;;   within the dictionary provided.
;; sum-amicable-numbers: (listof (list Nat Nat)) -> Nat

(define (sum-amicable-numbers number-dict)
  (cond [(empty? number-dict) 0]
        [(member? (reverse (first number-dict)) (rest number-dict))
         (+ (first (first number-dict)) (second (first number-dict))
            (sum-amicable-numbers (remove (reverse (first number-dict))
                                          (rest number-dict))))]
        [else (sum-amicable-numbers (rest number-dict))]))


;(sum-amicable-numbers (map (lambda (x) (list x (factor-sum x)))
;                           (build-list 9999 add1)))


;; ==== Question 22 ========================


;(define long-name-list '("MARY" "PATRICIA" "LINDA" "BARBARA" "ELIZABETH" "JENNIFER" "MARIA" "SUSAN" "MARGARET" "DOROTHY" "LISA" "NANCY" "KAREN" "BETTY" "HELEN" "SANDRA" "DONNA" "CAROL" "RUTH" "SHARON" "MICHELLE" "LAURA" "SARAH" "KIMBERLY" "DEBORAH" "JESSICA" "SHIRLEY" "CYNTHIA" "ANGELA" "MELISSA" "BRENDA" "AMY" "ANNA" "REBECCA" "VIRGINIA" "KATHLEEN" "PAMELA" "MARTHA" "DEBRA" "AMANDA" "STEPHANIE" "CAROLYN" "CHRISTINE" "MARIE" "JANET" "CATHERINE" "FRANCES" "ANN" "JOYCE" "DIANE" "ALICE" "JULIE" "HEATHER" "TERESA" "DORIS" "GLORIA" "EVELYN" "JEAN" "CHERYL" "MILDRED" "KATHERINE" "JOAN" "ASHLEY" "JUDITH" "ROSE" "JANICE" "KELLY" "NICOLE" "JUDY" "CHRISTINA" "KATHY" "THERESA" "BEVERLY" "DENISE" "TAMMY" "IRENE" "JANE" "LORI" "RACHEL" "MARILYN" "ANDREA" "KATHRYN" "LOUISE" "SARA" "ANNE" "JACQUELINE" "WANDA" "BONNIE" "JULIA" "RUBY" "LOIS" "TINA" "PHYLLIS" "NORMA" "PAULA" "DIANA" "ANNIE" "LILLIAN" "EMILY" "ROBIN" "PEGGY" "CRYSTAL" "GLADYS" "RITA" "DAWN" "CONNIE" "FLORENCE" "TRACY" "EDNA" "TIFFANY" "CARMEN" "ROSA" "CINDY" "GRACE" "WENDY" "VICTORIA" "EDITH" "KIM" "SHERRY" "SYLVIA" "JOSEPHINE" "THELMA" "SHANNON" "SHEILA" "ETHEL" "ELLEN" "ELAINE" "MARJORIE" "CARRIE" "CHARLOTTE" "MONICA" "ESTHER" "PAULINE" "EMMA" "JUANITA" "ANITA" "RHONDA" "HAZEL" "AMBER" "EVA" "DEBBIE" "APRIL" "LESLIE" "CLARA" "LUCILLE" "JAMIE" "JOANNE" "ELEANOR" "VALERIE" "DANIELLE" "MEGAN" "ALICIA" "SUZANNE" "MICHELE" "GAIL" "BERTHA" "DARLENE" "VERONICA" "JILL" "ERIN" "GERALDINE" "LAUREN" "CATHY" "JOANN" "LORRAINE" "LYNN" "SALLY" "REGINA" "ERICA" "BEATRICE" "DOLORES" "BERNICE" "AUDREY" "YVONNE" "ANNETTE" "JUNE" "SAMANTHA" "MARION" "DANA" "STACY" "ANA" "RENEE" "IDA" "VIVIAN" "ROBERTA" "HOLLY" "BRITTANY" "MELANIE" "LORETTA" "YOLANDA" "JEANETTE" "LAURIE" "KATIE" "KRISTEN" "VANESSA" "ALMA" "SUE" "ELSIE" "BETH" "JEANNE" "VICKI" "CARLA" "TARA" "ROSEMARY" "EILEEN" "TERRI" "GERTRUDE" "LUCY" "TONYA" "ELLA" "STACEY" "WILMA" "GINA" "KRISTIN" "JESSIE" "NATALIE" "AGNES" "VERA" "WILLIE" "CHARLENE" "BESSIE" "DELORES" "MELINDA" "PEARL" "ARLENE" "MAUREEN" "COLLEEN" "ALLISON" "TAMARA" "JOY" "GEORGIA" "CONSTANCE" "LILLIE" "CLAUDIA" "JACKIE" "MARCIA" "TANYA" "NELLIE" "MINNIE" "MARLENE" "HEIDI" "GLENDA" "LYDIA" "VIOLA" "COURTNEY" "MARIAN" "STELLA" "CAROLINE" "DORA" "JO" "VICKIE" "MATTIE" "TERRY" "MAXINE" "IRMA" "MABEL" "MARSHA" "MYRTLE" "LENA" "CHRISTY" "DEANNA" "PATSY" "HILDA" "GWENDOLYN" "JENNIE" "NORA" "MARGIE" "NINA" "CASSANDRA" "LEAH" "PENNY" "KAY" "PRISCILLA" "NAOMI" "CAROLE" "BRANDY" "OLGA" "BILLIE" "DIANNE" "TRACEY" "LEONA" "JENNY" "FELICIA" "SONIA" "MIRIAM" "VELMA" "BECKY" "BOBBIE" "VIOLET" "KRISTINA" "TONI" "MISTY" "MAE" "SHELLY" "DAISY" "RAMONA" "SHERRI" "ERIKA" "KATRINA" "CLAIRE" "LINDSEY" "LINDSAY" "GENEVA" "GUADALUPE" "BELINDA" "MARGARITA" "SHERYL" "CORA" "FAYE" "ADA" "NATASHA" "SABRINA" "ISABEL" "MARGUERITE" "HATTIE" "HARRIET" "MOLLY" "CECILIA" "KRISTI" "BRANDI" "BLANCHE" "SANDY" "ROSIE" "JOANNA" "IRIS" "EUNICE" "ANGIE" "INEZ" "LYNDA" "MADELINE" "AMELIA" "ALBERTA" "GENEVIEVE" "MONIQUE" "JODI" "JANIE" "MAGGIE" "KAYLA" "SONYA" "JAN" "LEE" "KRISTINE" "CANDACE" "FANNIE" "MARYANN" "OPAL" "ALISON" "YVETTE" "MELODY" "LUZ" "SUSIE" "OLIVIA" "FLORA" "SHELLEY" "KRISTY" "MAMIE" "LULA" "LOLA" "VERNA" "BEULAH" "ANTOINETTE" "CANDICE" "JUANA" "JEANNETTE" "PAM" "KELLI" "HANNAH" "WHITNEY" "BRIDGET" "KARLA" "CELIA" "LATOYA" "PATTY" "SHELIA" "GAYLE" "DELLA" "VICKY" "LYNNE" "SHERI" "MARIANNE" "KARA" "JACQUELYN" "ERMA" "BLANCA" "MYRA" "LETICIA" "PAT" "KRISTA" "ROXANNE" "ANGELICA" "JOHNNIE" "ROBYN" "FRANCIS" "ADRIENNE" "ROSALIE" "ALEXANDRA" "BROOKE" "BETHANY" "SADIE" "BERNADETTE" "TRACI" "JODY" "KENDRA" "JASMINE" "NICHOLE" "RACHAEL" "CHELSEA" "MABLE" "ERNESTINE" "MURIEL" "MARCELLA" "ELENA" "KRYSTAL" "ANGELINA" "NADINE" "KARI" "ESTELLE" "DIANNA" "PAULETTE" "LORA" "MONA" "DOREEN" "ROSEMARIE" "ANGEL" "DESIREE" "ANTONIA" "HOPE" "GINGER" "JANIS" "BETSY" "CHRISTIE" "FREDA" "MERCEDES" "MEREDITH" "LYNETTE" "TERI" "CRISTINA" "EULA" "LEIGH" "MEGHAN" "SOPHIA" "ELOISE" "ROCHELLE" "GRETCHEN" "CECELIA" "RAQUEL" "HENRIETTA" "ALYSSA" "JANA" "KELLEY" "GWEN" "KERRY" "JENNA" "TRICIA" "LAVERNE" "OLIVE" "ALEXIS" "TASHA" "SILVIA" "ELVIRA" "CASEY" "DELIA" "SOPHIE" "KATE" "PATTI" "LORENA" "KELLIE" "SONJA" "LILA" "LANA" "DARLA" "MAY" "MINDY" "ESSIE" "MANDY" "LORENE" "ELSA" "JOSEFINA" "JEANNIE" "MIRANDA" "DIXIE" "LUCIA" "MARTA" "FAITH" "LELA" "JOHANNA" "SHARI" "CAMILLE" "TAMI" "SHAWNA" "ELISA" "EBONY" "MELBA" "ORA" "NETTIE" "TABITHA" "OLLIE" "JAIME" "WINIFRED" "KRISTIE" "MARINA" "ALISHA" "AIMEE" "RENA" "MYRNA" "MARLA" "TAMMIE" "LATASHA" "BONITA" "PATRICE" "RONDA" "SHERRIE" "ADDIE" "FRANCINE" "DELORIS" "STACIE" "ADRIANA" "CHERI" "SHELBY" "ABIGAIL" "CELESTE" "JEWEL" "CARA" "ADELE" "REBEKAH" "LUCINDA" "DORTHY" "CHRIS" "EFFIE" "TRINA" "REBA" "SHAWN" "SALLIE" "AURORA" "LENORA" "ETTA" "LOTTIE" "KERRI" "TRISHA" "NIKKI" "ESTELLA" "FRANCISCA" "JOSIE" "TRACIE" "MARISSA" "KARIN" "BRITTNEY" "JANELLE" "LOURDES" "LAUREL" "HELENE" "FERN" "ELVA" "CORINNE" "KELSEY" "INA" "BETTIE" "ELISABETH" "AIDA" "CAITLIN" "INGRID" "IVA" "EUGENIA" "CHRISTA" "GOLDIE" "CASSIE" "MAUDE" "JENIFER" "THERESE" "FRANKIE" "DENA" "LORNA" "JANETTE" "LATONYA" "CANDY" "MORGAN" "CONSUELO" "TAMIKA" "ROSETTA" "DEBORA" "CHERIE" "POLLY" "DINA" "JEWELL" "FAY" "JILLIAN" "DOROTHEA" "NELL" "TRUDY" "ESPERANZA" "PATRICA" "KIMBERLEY" "SHANNA" "HELENA" "CAROLINA" "CLEO" "STEFANIE" "ROSARIO" "OLA" "JANINE" "MOLLIE" "LUPE" "ALISA" "LOU" "MARIBEL" "SUSANNE" "BETTE" "SUSANA" "ELISE" "CECILE" "ISABELLE" "LESLEY" "JOCELYN" "PAIGE" "JONI" "RACHELLE" "LEOLA" "DAPHNE" "ALTA" "ESTER" "PETRA" "GRACIELA" "IMOGENE" "JOLENE" "KEISHA" "LACEY" "GLENNA" "GABRIELA" "KERI" "URSULA" "LIZZIE" "KIRSTEN" "SHANA" "ADELINE" "MAYRA" "JAYNE" "JACLYN" "GRACIE" "SONDRA" "CARMELA" "MARISA" "ROSALIND" "CHARITY" "TONIA" "BEATRIZ" "MARISOL" "CLARICE" "JEANINE" "SHEENA" "ANGELINE" "FRIEDA" "LILY" "ROBBIE" "SHAUNA" "MILLIE" "CLAUDETTE" "CATHLEEN" "ANGELIA" "GABRIELLE" "AUTUMN" "KATHARINE" "SUMMER" "JODIE" "STACI" "LEA" "CHRISTI" "JIMMIE" "JUSTINE" "ELMA" "LUELLA" "MARGRET" "DOMINIQUE" "SOCORRO" "RENE" "MARTINA" "MARGO" "MAVIS" "CALLIE" "BOBBI" "MARITZA" "LUCILE" "LEANNE" "JEANNINE" "DEANA" "AILEEN" "LORIE" "LADONNA" "WILLA" "MANUELA" "GALE" "SELMA" "DOLLY" "SYBIL" "ABBY" "LARA" "DALE" "IVY" "DEE" "WINNIE" "MARCY" "LUISA" "JERI" "MAGDALENA" "OFELIA" "MEAGAN" "AUDRA" "MATILDA" "LEILA" "CORNELIA" "BIANCA" "SIMONE" "BETTYE" "RANDI" "VIRGIE" "LATISHA" "BARBRA" "GEORGINA" "ELIZA" "LEANN" "BRIDGETTE" "RHODA" "HALEY" "ADELA" "NOLA" "BERNADINE" "FLOSSIE" "ILA" "GRETA" "RUTHIE" "NELDA" "MINERVA" "LILLY" "TERRIE" "LETHA" "HILARY" "ESTELA" "VALARIE" "BRIANNA" "ROSALYN" "EARLINE" "CATALINA" "AVA" "MIA" "CLARISSA" "LIDIA" "CORRINE" "ALEXANDRIA" "CONCEPCION" "TIA" "SHARRON" "RAE" "DONA" "ERICKA" "JAMI" "ELNORA" "CHANDRA" "LENORE" "NEVA" "MARYLOU" "MELISA" "TABATHA" "SERENA" "AVIS" "ALLIE" "SOFIA" "JEANIE" "ODESSA" "NANNIE" "HARRIETT" "LORAINE" "PENELOPE" "MILAGROS" "EMILIA" "BENITA" "ALLYSON" "ASHLEE" "TANIA" "TOMMIE" "ESMERALDA" "KARINA" "EVE" "PEARLIE" "ZELMA" "MALINDA" "NOREEN" "TAMEKA" "SAUNDRA" "HILLARY" "AMIE" "ALTHEA" "ROSALINDA" "JORDAN" "LILIA" "ALANA" "GAY" "CLARE" "ALEJANDRA" "ELINOR" "MICHAEL" "LORRIE" "JERRI" "DARCY" "EARNESTINE" "CARMELLA" "TAYLOR" "NOEMI" "MARCIE" "LIZA" "ANNABELLE" "LOUISA" "EARLENE" "MALLORY" "CARLENE" "NITA" "SELENA" "TANISHA" "KATY" "JULIANNE" "JOHN" "LAKISHA" "EDWINA" "MARICELA" "MARGERY" "KENYA" "DOLLIE" "ROXIE" "ROSLYN" "KATHRINE" "NANETTE" "CHARMAINE" "LAVONNE" "ILENE" "KRIS" "TAMMI" "SUZETTE" "CORINE" "KAYE" "JERRY" "MERLE" "CHRYSTAL" "LINA" "DEANNE" "LILIAN" "JULIANA" "ALINE" "LUANN" "KASEY" "MARYANNE" "EVANGELINE" "COLETTE" "MELVA" "LAWANDA" "YESENIA" "NADIA" "MADGE" "KATHIE" "EDDIE" "OPHELIA" "VALERIA" "NONA" "MITZI" "MARI" "GEORGETTE" "CLAUDINE" "FRAN" "ALISSA" "ROSEANN" "LAKEISHA" "SUSANNA" "REVA" "DEIDRE" "CHASITY" "SHEREE" "CARLY" "JAMES" "ELVIA" "ALYCE" "DEIRDRE" "GENA" "BRIANA" "ARACELI" "KATELYN" "ROSANNE" "WENDI" "TESSA" "BERTA" "MARVA" "IMELDA" "MARIETTA" "MARCI" "LEONOR" "ARLINE" "SASHA" "MADELYN" "JANNA" "JULIETTE" "DEENA" "AURELIA" "JOSEFA" "AUGUSTA" "LILIANA" "YOUNG" "CHRISTIAN" "LESSIE" "AMALIA" "SAVANNAH" "ANASTASIA" "VILMA" "NATALIA" "ROSELLA" "LYNNETTE" "CORINA" "ALFREDA" "LEANNA" "CAREY" "AMPARO" "COLEEN" "TAMRA" "AISHA" "WILDA" "KARYN" "CHERRY" "QUEEN" "MAURA" "MAI" "EVANGELINA" "ROSANNA" "HALLIE" "ERNA" "ENID" "MARIANA" "LACY" "JULIET" "JACKLYN" "FREIDA" "MADELEINE" "MARA" "HESTER" "CATHRYN" "LELIA" "CASANDRA" "BRIDGETT" "ANGELITA" "JANNIE" "DIONNE" "ANNMARIE" "KATINA" "BERYL" "PHOEBE" "MILLICENT" "KATHERYN" "DIANN" "CARISSA" "MARYELLEN" "LIZ" "LAURI" "HELGA" "GILDA" "ADRIAN" "RHEA" "MARQUITA" "HOLLIE" "TISHA" "TAMERA" "ANGELIQUE" "FRANCESCA" "BRITNEY" "KAITLIN" "LOLITA" "FLORINE" "ROWENA" "REYNA" "TWILA" "FANNY" "JANELL" "INES" "CONCETTA" "BERTIE" "ALBA" "BRIGITTE" "ALYSON" "VONDA" "PANSY" "ELBA" "NOELLE" "LETITIA" "KITTY" "DEANN" "BRANDIE" "LOUELLA" "LETA" "FELECIA" "SHARLENE" "LESA" "BEVERLEY" "ROBERT" "ISABELLA" "HERMINIA" "TERRA" "CELINA" "TORI" "OCTAVIA" "JADE" "DENICE" "GERMAINE" "SIERRA" "MICHELL" "CORTNEY" "NELLY" "DORETHA" "SYDNEY" "DEIDRA" "MONIKA" "LASHONDA" "JUDI" "CHELSEY" "ANTIONETTE" "MARGOT" "BOBBY" "ADELAIDE" "NAN" "LEEANN" "ELISHA" "DESSIE" "LIBBY" "KATHI" "GAYLA" "LATANYA" "MINA" "MELLISA" "KIMBERLEE" "JASMIN" "RENAE" "ZELDA" "ELDA" "MA" "JUSTINA" "GUSSIE" "EMILIE" "CAMILLA" "ABBIE" "ROCIO" "KAITLYN" "JESSE" "EDYTHE" "ASHLEIGH" "SELINA" "LAKESHA" "GERI" "ALLENE" "PAMALA" "MICHAELA" "DAYNA" "CARYN" "ROSALIA" "SUN" "JACQULINE" "REBECA" "MARYBETH" "KRYSTLE" "IOLA" "DOTTIE" "BENNIE" "BELLE" "AUBREY" "GRISELDA" "ERNESTINA" "ELIDA" "ADRIANNE" "DEMETRIA" "DELMA" "CHONG" "JAQUELINE" "DESTINY" "ARLEEN" "VIRGINA" "RETHA" "FATIMA" "TILLIE" "ELEANORE" "CARI" "TREVA" "BIRDIE" "WILHELMINA" "ROSALEE" "MAURINE" "LATRICE" "YONG" "JENA" "TARYN" "ELIA" "DEBBY" "MAUDIE" "JEANNA" "DELILAH" "CATRINA" "SHONDA" "HORTENCIA" "THEODORA" "TERESITA" "ROBBIN" "DANETTE" "MARYJANE" "FREDDIE" "DELPHINE" "BRIANNE" "NILDA" "DANNA" "CINDI" "BESS" "IONA" "HANNA" "ARIEL" "WINONA" "VIDA" "ROSITA" "MARIANNA" "WILLIAM" "RACHEAL" "GUILLERMINA" "ELOISA" "CELESTINE" "CAREN" "MALISSA" "LONA" "CHANTEL" "SHELLIE" "MARISELA" "LEORA" "AGATHA" "SOLEDAD" "MIGDALIA" "IVETTE" "CHRISTEN" "ATHENA" "JANEL" "CHLOE" "VEDA" "PATTIE" "TESSIE" "TERA" "MARILYNN" "LUCRETIA" "KARRIE" "DINAH" "DANIELA" "ALECIA" "ADELINA" "VERNICE" "SHIELA" "PORTIA" "MERRY" "LASHAWN" "DEVON" "DARA" "TAWANA" "OMA" "VERDA" "CHRISTIN" "ALENE" "ZELLA" "SANDI" "RAFAELA" "MAYA" "KIRA" "CANDIDA" "ALVINA" "SUZAN" "SHAYLA" "LYN" "LETTIE" "ALVA" "SAMATHA" "ORALIA" "MATILDE" "MADONNA" "LARISSA" "VESTA" "RENITA" "INDIA" "DELOIS" "SHANDA" "PHILLIS" "LORRI" "ERLINDA" "CRUZ" "CATHRINE" "BARB" "ZOE" "ISABELL" "IONE" "GISELA" "CHARLIE" "VALENCIA" "ROXANNA" "MAYME" "KISHA" "ELLIE" "MELLISSA" "DORRIS" "DALIA" "BELLA" "ANNETTA" "ZOILA" "RETA" "REINA" "LAURETTA" "KYLIE" "CHRISTAL" "PILAR" "CHARLA" "ELISSA" "TIFFANI" "TANA" "PAULINA" "LEOTA" "BREANNA" "JAYME" "CARMEL" "VERNELL" "TOMASA" "MANDI" "DOMINGA" "SANTA" "MELODIE" "LURA" "ALEXA" "TAMELA" "RYAN" "MIRNA" "KERRIE" "VENUS" "NOEL" "FELICITA" "CRISTY" "CARMELITA" "BERNIECE" "ANNEMARIE" "TIARA" "ROSEANNE" "MISSY" "CORI" "ROXANA" "PRICILLA" "KRISTAL" "JUNG" "ELYSE" "HAYDEE" "ALETHA" "BETTINA" "MARGE" "GILLIAN" "FILOMENA" "CHARLES" "ZENAIDA" "HARRIETTE" "CARIDAD" "VADA" "UNA" "ARETHA" "PEARLINE" "MARJORY" "MARCELA" "FLOR" "EVETTE" "ELOUISE" "ALINA" "TRINIDAD" "DAVID" "DAMARIS" "CATHARINE" "CARROLL" "BELVA" "NAKIA" "MARLENA" "LUANNE" "LORINE" "KARON" "DORENE" "DANITA" "BRENNA" "TATIANA" "SAMMIE" "LOUANN" "LOREN" "JULIANNA" "ANDRIA" "PHILOMENA" "LUCILA" "LEONORA" "DOVIE" "ROMONA" "MIMI" "JACQUELIN" "GAYE" "TONJA" "MISTI" "JOE" "GENE" "CHASTITY" "STACIA" "ROXANN" "MICAELA" "NIKITA" "MEI" "VELDA" "MARLYS" "JOHNNA" "AURA" "LAVERN" "IVONNE" "HAYLEY" "NICKI" "MAJORIE" "HERLINDA" "GEORGE" "ALPHA" "YADIRA" "PERLA" "GREGORIA" "DANIEL" "ANTONETTE" "SHELLI" "MOZELLE" "MARIAH" "JOELLE" "CORDELIA" "JOSETTE" "CHIQUITA" "TRISTA" "LOUIS" "LAQUITA" "GEORGIANA" "CANDI" "SHANON" "LONNIE" "HILDEGARD" "CECIL" "VALENTINA" "STEPHANY" "MAGDA" "KAROL" "GERRY" "GABRIELLA" "TIANA" "ROMA" "RICHELLE" "RAY" "PRINCESS" "OLETA" "JACQUE" "IDELLA" "ALAINA" "SUZANNA" "JOVITA" "BLAIR" "TOSHA" "RAVEN" "NEREIDA" "MARLYN" "KYLA" "JOSEPH" "DELFINA" "TENA" "STEPHENIE" "SABINA" "NATHALIE" "MARCELLE" "GERTIE" "DARLEEN" "THEA" "SHARONDA" "SHANTEL" "BELEN" "VENESSA" "ROSALINA" "ONA" "GENOVEVA" "COREY" "CLEMENTINE" "ROSALBA" "RENATE" "RENATA" "MI" "IVORY" "GEORGIANNA" "FLOY" "DORCAS" "ARIANA" "TYRA" "THEDA" "MARIAM" "JULI" "JESICA" "DONNIE" "VIKKI" "VERLA" "ROSELYN" "MELVINA" "JANNETTE" "GINNY" "DEBRAH" "CORRIE" "ASIA" "VIOLETA" "MYRTIS" "LATRICIA" "COLLETTE" "CHARLEEN" "ANISSA" "VIVIANA" "TWYLA" "PRECIOUS" "NEDRA" "LATONIA" "LAN" "HELLEN" "FABIOLA" "ANNAMARIE" "ADELL" "SHARYN" "CHANTAL" "NIKI" "MAUD" "LIZETTE" "LINDY" "KIA" "KESHA" "JEANA" "DANELLE" "CHARLINE" "CHANEL" "CARROL" "VALORIE" "LIA" "DORTHA" "CRISTAL" "SUNNY" "LEONE" "LEILANI" "GERRI" "DEBI" "ANDRA" "KESHIA" "IMA" "EULALIA" "EASTER" "DULCE" "NATIVIDAD" "LINNIE" "KAMI" "GEORGIE" "CATINA" "BROOK" "ALDA" "WINNIFRED" "SHARLA" "RUTHANN" "MEAGHAN" "MAGDALENE" "LISSETTE" "ADELAIDA" "VENITA" "TRENA" "SHIRLENE" "SHAMEKA" "ELIZEBETH" "DIAN" "SHANTA" "MICKEY" "LATOSHA" "CARLOTTA" "WINDY" "SOON" "ROSINA" "MARIANN" "LEISA" "JONNIE" "DAWNA" "CATHIE" "BILLY" "ASTRID" "SIDNEY" "LAUREEN" "JANEEN" "HOLLI" "FAWN" "VICKEY" "TERESSA" "SHANTE" "RUBYE" "MARCELINA" "CHANDA" "CARY" "TERESE" "SCARLETT" "MARTY" "MARNIE" "LULU" "LISETTE" "JENIFFER" "ELENOR" "DORINDA" "DONITA" "CARMAN" "BERNITA" "ALTAGRACIA" "ALETA" "ADRIANNA" "ZORAIDA" "RONNIE" "NICOLA" "LYNDSEY" "KENDALL" "JANINA" "CHRISSY" "AMI" "STARLA" "PHYLIS" "PHUONG" "KYRA" "CHARISSE" "BLANCH" "SANJUANITA" "RONA" "NANCI" "MARILEE" "MARANDA" "CORY" "BRIGETTE" "SANJUANA" "MARITA" "KASSANDRA" "JOYCELYN" "IRA" "FELIPA" "CHELSIE" "BONNY" "MIREYA" "LORENZA" "KYONG" "ILEANA" "CANDELARIA" "TONY" "TOBY" "SHERIE" "OK" "MARK" "LUCIE" "LEATRICE" "LAKESHIA" "GERDA" "EDIE" "BAMBI" "MARYLIN" "LAVON" "HORTENSE" "GARNET" "EVIE" "TRESSA" "SHAYNA" "LAVINA" "KYUNG" "JEANETTA" "SHERRILL" "SHARA" "PHYLISS" "MITTIE" "ANABEL" "ALESIA" "THUY" "TAWANDA" "RICHARD" "JOANIE" "TIFFANIE" "LASHANDA" "KARISSA" "ENRIQUETA" "DARIA" "DANIELLA" "CORINNA" "ALANNA" "ABBEY" "ROXANE" "ROSEANNA" "MAGNOLIA" "LIDA" "KYLE" "JOELLEN" "ERA" "CORAL" "CARLEEN" "TRESA" "PEGGIE" "NOVELLA" "NILA" "MAYBELLE" "JENELLE" "CARINA" "NOVA" "MELINA" "MARQUERITE" "MARGARETTE" "JOSEPHINA" "EVONNE" "DEVIN" "CINTHIA" "ALBINA" "TOYA" "TAWNYA" "SHERITA" "SANTOS" "MYRIAM" "LIZABETH" "LISE" "KEELY" "JENNI" "GISELLE" "CHERYLE" "ARDITH" "ARDIS" "ALESHA" "ADRIANE" "SHAINA" "LINNEA" "KAROLYN" "HONG" "FLORIDA" "FELISHA" "DORI" "DARCI" "ARTIE" "ARMIDA" "ZOLA" "XIOMARA" "VERGIE" "SHAMIKA" "NENA" "NANNETTE" "MAXIE" "LOVIE" "JEANE" "JAIMIE" "INGE" "FARRAH" "ELAINA" "CAITLYN" "STARR" "FELICITAS" "CHERLY" "CARYL" "YOLONDA" "YASMIN" "TEENA" "PRUDENCE" "PENNIE" "NYDIA" "MACKENZIE" "ORPHA" "MARVEL" "LIZBETH" "LAURETTE" "JERRIE" "HERMELINDA" "CAROLEE" "TIERRA" "MIRIAN" "META" "MELONY" "KORI" "JENNETTE" "JAMILA" "ENA" "ANH" "YOSHIKO" "SUSANNAH" "SALINA" "RHIANNON" "JOLEEN" "CRISTINE" "ASHTON" "ARACELY" "TOMEKA" "SHALONDA" "MARTI" "LACIE" "KALA" "JADA" "ILSE" "HAILEY" "BRITTANI" "ZONA" "SYBLE" "SHERRYL" "RANDY" "NIDIA" "MARLO" "KANDICE" "KANDI" "DEB" "DEAN" "AMERICA" "ALYCIA" "TOMMY" "RONNA" "NORENE" "MERCY" "JOSE" "INGEBORG" "GIOVANNA" "GEMMA" "CHRISTEL" "AUDRY" "ZORA" "VITA" "VAN" "TRISH" "STEPHAINE" "SHIRLEE" "SHANIKA" "MELONIE" "MAZIE" "JAZMIN" "INGA" "HOA" "HETTIE" "GERALYN" "FONDA" "ESTRELLA" "ADELLA" "SU" "SARITA" "RINA" "MILISSA" "MARIBETH" "GOLDA" "EVON" "ETHELYN" "ENEDINA" "CHERISE" "CHANA" "VELVA" "TAWANNA" "SADE" "MIRTA" "LI" "KARIE" "JACINTA" "ELNA" "DAVINA" "CIERRA" "ASHLIE" "ALBERTHA" "TANESHA" "STEPHANI" "NELLE" "MINDI" "LU" "LORINDA" "LARUE" "FLORENE" "DEMETRA" "DEDRA" "CIARA" "CHANTELLE" "ASHLY" "SUZY" "ROSALVA" "NOELIA" "LYDA" "LEATHA" "KRYSTYNA" "KRISTAN" "KARRI" "DARLINE" "DARCIE" "CINDA" "CHEYENNE" "CHERRIE" "AWILDA" "ALMEDA" "ROLANDA" "LANETTE" "JERILYN" "GISELE" "EVALYN" "CYNDI" "CLETA" "CARIN" "ZINA" "ZENA" "VELIA" "TANIKA" "PAUL" "CHARISSA" "THOMAS" "TALIA" "MARGARETE" "LAVONDA" "KAYLEE" "KATHLENE" "JONNA" "IRENA" "ILONA" "IDALIA" "CANDIS" "CANDANCE" "BRANDEE" "ANITRA" "ALIDA" "SIGRID" "NICOLETTE" "MARYJO" "LINETTE" "HEDWIG" "CHRISTIANA" "CASSIDY" "ALEXIA" "TRESSIE" "MODESTA" "LUPITA" "LITA" "GLADIS" "EVELIA" "DAVIDA" "CHERRI" "CECILY" "ASHELY" "ANNABEL" "AGUSTINA" "WANITA" "SHIRLY" "ROSAURA" "HULDA" "EUN" "BAILEY" "YETTA" "VERONA" "THOMASINA" "SIBYL" "SHANNAN" "MECHELLE" "LUE" "LEANDRA" "LANI" "KYLEE" "KANDY" "JOLYNN" "FERNE" "EBONI" "CORENE" "ALYSIA" "ZULA" "NADA" "MOIRA" "LYNDSAY" "LORRETTA" "JUAN" "JAMMIE" "HORTENSIA" "GAYNELL" "CAMERON" "ADRIA" "VINA" "VICENTA" "TANGELA" "STEPHINE" "NORINE" "NELLA" "LIANA" "LESLEE" "KIMBERELY" "ILIANA" "GLORY" "FELICA" "EMOGENE" "ELFRIEDE" "EDEN" "EARTHA" "CARMA" "BEA" "OCIE" "MARRY" "LENNIE" "KIARA" "JACALYN" "CARLOTA" "ARIELLE" "YU" "STAR" "OTILIA" "KIRSTIN" "KACEY" "JOHNETTA" "JOEY" "JOETTA" "JERALDINE" "JAUNITA" "ELANA" "DORTHEA" "CAMI" "AMADA" "ADELIA" "VERNITA" "TAMAR" "SIOBHAN" "RENEA" "RASHIDA" "OUIDA" "ODELL" "NILSA" "MERYL" "KRISTYN" "JULIETA" "DANICA" "BREANNE" "AUREA" "ANGLEA" "SHERRON" "ODETTE" "MALIA" "LORELEI" "LIN" "LEESA" "KENNA" "KATHLYN" "FIONA" "CHARLETTE" "SUZIE" "SHANTELL" "SABRA" "RACQUEL" "MYONG" "MIRA" "MARTINE" "LUCIENNE" "LAVADA" "JULIANN" "JOHNIE" "ELVERA" "DELPHIA" "CLAIR" "CHRISTIANE" "CHAROLETTE" "CARRI" "AUGUSTINE" "ASHA" "ANGELLA" "PAOLA" "NINFA" "LEDA" "LAI" "EDA" "SUNSHINE" "STEFANI" "SHANELL" "PALMA" "MACHELLE" "LISSA" "KECIA" "KATHRYNE" "KARLENE" "JULISSA" "JETTIE" "JENNIFFER" "HUI" "CORRINA" "CHRISTOPHER" "CAROLANN" "ALENA" "TESS" "ROSARIA" "MYRTICE" "MARYLEE" "LIANE" "KENYATTA" "JUDIE" "JANEY" "IN" "ELMIRA" "ELDORA" "DENNA" "CRISTI" "CATHI" "ZAIDA" "VONNIE" "VIVA" "VERNIE" "ROSALINE" "MARIELA" "LUCIANA" "LESLI" "KARAN" "FELICE" "DENEEN" "ADINA" "WYNONA" "TARSHA" "SHERON" "SHASTA" "SHANITA" "SHANI" "SHANDRA" "RANDA" "PINKIE" "PARIS" "NELIDA" "MARILOU" "LYLA" "LAURENE" "LACI" "JOI" "JANENE" "DOROTHA" "DANIELE" "DANI" "CAROLYNN" "CARLYN" "BERENICE" "AYESHA" "ANNELIESE" "ALETHEA" "THERSA" "TAMIKO" "RUFINA" "OLIVA" "MOZELL" "MARYLYN" "MADISON" "KRISTIAN" "KATHYRN" "KASANDRA" "KANDACE" "JANAE" "GABRIEL" "DOMENICA" "DEBBRA" "DANNIELLE" "CHUN" "BUFFY" "BARBIE" "ARCELIA" "AJA" "ZENOBIA" "SHAREN" "SHAREE" "PATRICK" "PAGE" "MY" "LAVINIA" "KUM" "KACIE" "JACKELINE" "HUONG" "FELISA" "EMELIA" "ELEANORA" "CYTHIA" "CRISTIN" "CLYDE" "CLARIBEL" "CARON" "ANASTACIA" "ZULMA" "ZANDRA" "YOKO" "TENISHA" "SUSANN" "SHERILYN" "SHAY" "SHAWANDA" "SABINE" "ROMANA" "MATHILDA" "LINSEY" "KEIKO" "JOANA" "ISELA" "GRETTA" "GEORGETTA" "EUGENIE" "DUSTY" "DESIRAE" "DELORA" "CORAZON" "ANTONINA" "ANIKA" "WILLENE" "TRACEE" "TAMATHA" "REGAN" "NICHELLE" "MICKIE" "MAEGAN" "LUANA" "LANITA" "KELSIE" "EDELMIRA" "BREE" "AFTON" "TEODORA" "TAMIE" "SHENA" "MEG" "LINH" "KELI" "KACI" "DANYELLE" "BRITT" "ARLETTE" "ALBERTINE" "ADELLE" "TIFFINY" "STORMY" "SIMONA" "NUMBERS" "NICOLASA" "NICHOL" "NIA" "NAKISHA" "MEE" "MAIRA" "LOREEN" "KIZZY" "JOHNNY" "JAY" "FALLON" "CHRISTENE" "BOBBYE" "ANTHONY" "YING" "VINCENZA" "TANJA" "RUBIE" "RONI" "QUEENIE" "MARGARETT" "KIMBERLI" "IRMGARD" "IDELL" "HILMA" "EVELINA" "ESTA" "EMILEE" "DENNISE" "DANIA" "CARL" "CARIE" "ANTONIO" "WAI" "SANG" "RISA" "RIKKI" "PARTICIA" "MUI" "MASAKO" "MARIO" "LUVENIA" "LOREE" "LONI" "LIEN" "KEVIN" "GIGI" "FLORENCIA" "DORIAN" "DENITA" "DALLAS" "CHI" "BILLYE" "ALEXANDER" "TOMIKA" "SHARITA" "RANA" "NIKOLE" "NEOMA" "MARGARITE" "MADALYN" "LUCINA" "LAILA" "KALI" "JENETTE" "GABRIELE" "EVELYNE" "ELENORA" "CLEMENTINA" "ALEJANDRINA" "ZULEMA" "VIOLETTE" "VANNESSA" "THRESA" "RETTA" "PIA" "PATIENCE" "NOELLA" "NICKIE" "JONELL" "DELTA" "CHUNG" "CHAYA" "CAMELIA" "BETHEL" "ANYA" "ANDREW" "THANH" "SUZANN" "SPRING" "SHU" "MILA" "LILLA" "LAVERNA" "KEESHA" "KATTIE" "GIA" "GEORGENE" "EVELINE" "ESTELL" "ELIZBETH" "VIVIENNE" "VALLIE" "TRUDIE" "STEPHANE" "MICHEL" "MAGALY" "MADIE" "KENYETTA" "KARREN" "JANETTA" "HERMINE" "HARMONY" "DRUCILLA" "DEBBI" "CELESTINA" "CANDIE" "BRITNI" "BECKIE" "AMINA" "ZITA" "YUN" "YOLANDE" "VIVIEN" "VERNETTA" "TRUDI" "SOMMER" "PEARLE" "PATRINA" "OSSIE" "NICOLLE" "LOYCE" "LETTY" "LARISA" "KATHARINA" "JOSELYN" "JONELLE" "JENELL" "IESHA" "HEIDE" "FLORINDA" "FLORENTINA" "FLO" "ELODIA" "DORINE" "BRUNILDA" "BRIGID" "ASHLI" "ARDELLA" "TWANA" "THU" "TARAH" "SUNG" "SHEA" "SHAVON" "SHANE" "SERINA" "RAYNA" "RAMONITA" "NGA" "MARGURITE" "LUCRECIA" "KOURTNEY" "KATI" "JESUS" "JESENIA" "DIAMOND" "CRISTA" "AYANA" "ALICA" "ALIA" "VINNIE" "SUELLEN" "ROMELIA" "RACHELL" "PIPER" "OLYMPIA" "MICHIKO" "KATHALEEN" "JOLIE" "JESSI" "JANESSA" "HANA" "HA" "ELEASE" "CARLETTA" "BRITANY" "SHONA" "SALOME" "ROSAMOND" "REGENA" "RAINA" "NGOC" "NELIA" "LOUVENIA" "LESIA" "LATRINA" "LATICIA" "LARHONDA" "JINA" "JACKI" "HOLLIS" "HOLLEY" "EMMY" "DEEANN" "CORETTA" "ARNETTA" "VELVET" "THALIA" "SHANICE" "NETA" "MIKKI" "MICKI" "LONNA" "LEANA" "LASHUNDA" "KILEY" "JOYE" "JACQULYN" "IGNACIA" "HYUN" "HIROKO" "HENRY" "HENRIETTE" "ELAYNE" "DELINDA" "DARNELL" "DAHLIA" "COREEN" "CONSUELA" "CONCHITA" "CELINE" "BABETTE" "AYANNA" "ANETTE" "ALBERTINA" "SKYE" "SHAWNEE" "SHANEKA" "QUIANA" "PAMELIA" "MIN" "MERRI" "MERLENE" "MARGIT" "KIESHA" "KIERA" "KAYLENE" "JODEE" "JENISE" "ERLENE" "EMMIE" "ELSE" "DARYL" "DALILA" "DAISEY" "CODY" "CASIE" "BELIA" "BABARA" "VERSIE" "VANESA" "SHELBA" "SHAWNDA" "SAM" "NORMAN" "NIKIA" "NAOMA" "MARNA" "MARGERET" "MADALINE" "LAWANA" "KINDRA" "JUTTA" "JAZMINE" "JANETT" "HANNELORE" "GLENDORA" "GERTRUD" "GARNETT" "FREEDA" "FREDERICA" "FLORANCE" "FLAVIA" "DENNIS" "CARLINE" "BEVERLEE" "ANJANETTE" "VALDA" "TRINITY" "TAMALA" "STEVIE" "SHONNA" "SHA" "SARINA" "ONEIDA" "MICAH" "MERILYN" "MARLEEN" "LURLINE" "LENNA" "KATHERIN" "JIN" "JENI" "HAE" "GRACIA" "GLADY" "FARAH" "ERIC" "ENOLA" "EMA" "DOMINQUE" "DEVONA" "DELANA" "CECILA" "CAPRICE" "ALYSHA" "ALI" "ALETHIA" "VENA" "THERESIA" "TAWNY" "SONG" "SHAKIRA" "SAMARA" "SACHIKO" "RACHELE" "PAMELLA" "NICKY" "MARNI" "MARIEL" "MAREN" "MALISA" "LIGIA" "LERA" "LATORIA" "LARAE" "KIMBER" "KATHERN" "KAREY" "JENNEFER" "JANETH" "HALINA" "FREDIA" "DELISA" "DEBROAH" "CIERA" "CHIN" "ANGELIKA" "ANDREE" "ALTHA" "YEN" "VIVAN" "TERRESA" "TANNA" "SUK" "SUDIE" "SOO" "SIGNE" "SALENA" "RONNI" "REBBECCA" "MYRTIE" "MCKENZIE" "MALIKA" "MAIDA" "LOAN" "LEONARDA" "KAYLEIGH" "FRANCE" "ETHYL" "ELLYN" "DAYLE" "CAMMIE" "BRITTNI" "BIRGIT" "AVELINA" "ASUNCION" "ARIANNA" "AKIKO" "VENICE" "TYESHA" "TONIE" "TIESHA" "TAKISHA" "STEFFANIE" "SINDY" "SANTANA" "MEGHANN" "MANDA" "MACIE" "LADY" "KELLYE" "KELLEE" "JOSLYN" "JASON" "INGER" "INDIRA" "GLINDA" "GLENNIS" "FERNANDA" "FAUSTINA" "ENEIDA" "ELICIA" "DOT" "DIGNA" "DELL" "ARLETTA" "ANDRE" "WILLIA" "TAMMARA" "TABETHA" "SHERRELL" "SARI" "REFUGIO" "REBBECA" "PAULETTA" "NIEVES" "NATOSHA" "NAKITA" "MAMMIE" "KENISHA" "KAZUKO" "KASSIE" "GARY" "EARLEAN" "DAPHINE" "CORLISS" "CLOTILDE" "CAROLYNE" "BERNETTA" "AUGUSTINA" "AUDREA" "ANNIS" "ANNABELL" "YAN" "TENNILLE" "TAMICA" "SELENE" "SEAN" "ROSANA" "REGENIA" "QIANA" "MARKITA" "MACY" "LEEANNE" "LAURINE" "KYM" "JESSENIA" "JANITA" "GEORGINE" "GENIE" "EMIKO" "ELVIE" "DEANDRA" "DAGMAR" "CORIE" "COLLEN" "CHERISH" "ROMAINE" "PORSHA" "PEARLENE" "MICHELINE" "MERNA" "MARGORIE" "MARGARETTA" "LORE" "KENNETH" "JENINE" "HERMINA" "FREDERICKA" "ELKE" "DRUSILLA" "DORATHY" "DIONE" "DESIRE" "CELENA" "BRIGIDA" "ANGELES" "ALLEGRA" "THEO" "TAMEKIA" "SYNTHIA" "STEPHEN" "SOOK" "SLYVIA" "ROSANN" "REATHA" "RAYE" "MARQUETTA" "MARGART" "LING" "LAYLA" "KYMBERLY" "KIANA" "KAYLEEN" "KATLYN" "KARMEN" "JOELLA" "IRINA" "EMELDA" "ELENI" "DETRA" "CLEMMIE" "CHERYLL" "CHANTELL" "CATHEY" "ARNITA" "ARLA" "ANGLE" "ANGELIC" "ALYSE" "ZOFIA" "THOMASINE" "TENNIE" "SON" "SHERLY" "SHERLEY" "SHARYL" "REMEDIOS" "PETRINA" "NICKOLE" "MYUNG" "MYRLE" "MOZELLA" "LOUANNE" "LISHA" "LATIA" "LANE" "KRYSTA" "JULIENNE" "JOEL" "JEANENE" "JACQUALINE" "ISAURA" "GWENDA" "EARLEEN" "DONALD" "CLEOPATRA" "CARLIE" "AUDIE" "ANTONIETTA" "ALISE" "ALEX" "VERDELL" "VAL" "TYLER" "TOMOKO" "THAO" "TALISHA" "STEVEN" "SO" "SHEMIKA" "SHAUN" "SCARLET" "SAVANNA" "SANTINA" "ROSIA" "RAEANN" "ODILIA" "NANA" "MINNA" "MAGAN" "LYNELLE" "LE" "KARMA" "JOEANN" "IVANA" "INELL" "ILANA" "HYE" "HONEY" "HEE" "GUDRUN" "FRANK" "DREAMA" "CRISSY" "CHANTE" "CARMELINA" "ARVILLA" "ARTHUR" "ANNAMAE" "ALVERA" "ALEIDA" "AARON" "YEE" "YANIRA" "VANDA" "TIANNA" "TAM" "STEFANIA" "SHIRA" "PERRY" "NICOL" "NANCIE" "MONSERRATE" "MINH" "MELYNDA" "MELANY" "MATTHEW" "LOVELLA" "LAURE" "KIRBY" "KACY" "JACQUELYNN" "HYON" "GERTHA" "FRANCISCO" "ELIANA" "CHRISTENA" "CHRISTEEN" "CHARISE" "CATERINA" "CARLEY" "CANDYCE" "ARLENA" "AMMIE" "YANG" "WILLETTE" "VANITA" "TUYET" "TINY" "SYREETA" "SILVA" "SCOTT" "RONALD" "PENNEY" "NYLA" "MICHAL" "MAURICE" "MARYAM" "MARYA" "MAGEN" "LUDIE" "LOMA" "LIVIA" "LANELL" "KIMBERLIE" "JULEE" "DONETTA" "DIEDRA" "DENISHA" "DEANE" "DAWNE" "CLARINE" "CHERRYL" "BRONWYN" "BRANDON" "ALLA" "VALERY" "TONDA" "SUEANN" "SORAYA" "SHOSHANA" "SHELA" "SHARLEEN" "SHANELLE" "NERISSA" "MICHEAL" "MERIDITH" "MELLIE" "MAYE" "MAPLE" "MAGARET" "LUIS" "LILI" "LEONILA" "LEONIE" "LEEANNA" "LAVONIA" "LAVERA" "KRISTEL" "KATHEY" "KATHE" "JUSTIN" "JULIAN" "JIMMY" "JANN" "ILDA" "HILDRED" "HILDEGARDE" "GENIA" "FUMIKO" "EVELIN" "ERMELINDA" "ELLY" "DUNG" "DOLORIS" "DIONNA" "DANAE" "BERNEICE" "ANNICE" "ALIX" "VERENA" "VERDIE" "TRISTAN" "SHAWNNA" "SHAWANA" "SHAUNNA" "ROZELLA" "RANDEE" "RANAE" "MILAGRO" "LYNELL" "LUISE" "LOUIE" "LOIDA" "LISBETH" "KARLEEN" "JUNITA" "JONA" "ISIS" "HYACINTH" "HEDY" "GWENN" "ETHELENE" "ERLINE" "EDWARD" "DONYA" "DOMONIQUE" "DELICIA" "DANNETTE" "CICELY" "BRANDA" "BLYTHE" "BETHANN" "ASHLYN" "ANNALEE" "ALLINE" "YUKO" "VELLA" "TRANG" "TOWANDA" "TESHA" "SHERLYN" "NARCISA" "MIGUELINA" "MERI" "MAYBELL" "MARLANA" "MARGUERITA" "MADLYN" "LUNA" "LORY" "LORIANN" "LIBERTY" "LEONORE" "LEIGHANN" "LAURICE" "LATESHA" "LARONDA" "KATRICE" "KASIE" "KARL" "KALEY" "JADWIGA" "GLENNIE" "GEARLDINE" "FRANCINA" "EPIFANIA" "DYAN" "DORIE" "DIEDRE" "DENESE" "DEMETRICE" "DELENA" "DARBY" "CRISTIE" "CLEORA" "CATARINA" "CARISA" "BERNIE" "BARBERA" "ALMETA" "TRULA" "TEREASA" "SOLANGE" "SHEILAH" "SHAVONNE" "SANORA" "ROCHELL" "MATHILDE" "MARGARETA" "MAIA" "LYNSEY" "LAWANNA" "LAUNA" "KENA" "KEENA" "KATIA" "JAMEY" "GLYNDA" "GAYLENE" "ELVINA" "ELANOR" "DANUTA" "DANIKA" "CRISTEN" "CORDIE" "COLETTA" "CLARITA" "CARMON" "BRYNN" "AZUCENA" "AUNDREA" "ANGELE" "YI" "WALTER" "VERLIE" "VERLENE" "TAMESHA" "SILVANA" "SEBRINA" "SAMIRA" "REDA" "RAYLENE" "PENNI" "PANDORA" "NORAH" "NOMA" "MIREILLE" "MELISSIA" "MARYALICE" "LARAINE" "KIMBERY" "KARYL" "KARINE" "KAM" "JOLANDA" "JOHANA" "JESUSA" "JALEESA" "JAE" "JACQUELYNE" "IRISH" "ILUMINADA" "HILARIA" "HANH" "GENNIE" "FRANCIE" "FLORETTA" "EXIE" "EDDA" "DREMA" "DELPHA" "BEV" "BARBAR" "ASSUNTA" "ARDELL" "ANNALISA" "ALISIA" "YUKIKO" "YOLANDO" "WONDA" "WEI" "WALTRAUD" "VETA" "TEQUILA" "TEMEKA" "TAMEIKA" "SHIRLEEN" "SHENITA" "PIEDAD" "OZELLA" "MIRTHA" "MARILU" "KIMIKO" "JULIANE" "JENICE" "JEN" "JANAY" "JACQUILINE" "HILDE" "FE" "FAE" "EVAN" "EUGENE" "ELOIS" "ECHO" "DEVORAH" "CHAU" "BRINDA" "BETSEY" "ARMINDA" "ARACELIS" "APRYL" "ANNETT" "ALISHIA" "VEOLA" "USHA" "TOSHIKO" "THEOLA" "TASHIA" "TALITHA" "SHERY" "RUDY" "RENETTA" "REIKO" "RASHEEDA" "OMEGA" "OBDULIA" "MIKA" "MELAINE" "MEGGAN" "MARTIN" "MARLEN" "MARGET" "MARCELINE" "MANA" "MAGDALEN" "LIBRADA" "LEZLIE" "LEXIE" "LATASHIA" "LASANDRA" "KELLE" "ISIDRA" "ISA" "INOCENCIA" "GWYN" "FRANCOISE" "ERMINIA" "ERINN" "DIMPLE" "DEVORA" "CRISELDA" "ARMANDA" "ARIE" "ARIANE" "ANGELO" "ANGELENA" "ALLEN" "ALIZA" "ADRIENE" "ADALINE" "XOCHITL" "TWANNA" "TRAN" "TOMIKO" "TAMISHA" "TAISHA" "SUSY" "SIU" "RUTHA" "ROXY" "RHONA" "RAYMOND" "OTHA" "NORIKO" "NATASHIA" "MERRIE" "MELVIN" "MARINDA" "MARIKO" "MARGERT" "LORIS" "LIZZETTE" "LEISHA" "KAILA" "KA" "JOANNIE" "JERRICA" "JENE" "JANNET" "JANEE" "JACINDA" "HERTA" "ELENORE" "DORETTA" "DELAINE" "DANIELL" "CLAUDIE" "CHINA" "BRITTA" "APOLONIA" "AMBERLY" "ALEASE" "YURI" "YUK" "WEN" "WANETA" "UTE" "TOMI" "SHARRI" "SANDIE" "ROSELLE" "REYNALDA" "RAGUEL" "PHYLICIA" "PATRIA" "OLIMPIA" "ODELIA" "MITZIE" "MITCHELL" "MISS" "MINDA" "MIGNON" "MICA" "MENDY" "MARIVEL" "MAILE" "LYNETTA" "LAVETTE" "LAURYN" "LATRISHA" "LAKIESHA" "KIERSTEN" "KARY" "JOSPHINE" "JOLYN" "JETTA" "JANISE" "JACQUIE" "IVELISSE" "GLYNIS" "GIANNA" "GAYNELLE" "EMERALD" "DEMETRIUS" "DANYELL" "DANILLE" "DACIA" "CORALEE" "CHER" "CEOLA" "BRETT" "BELL" "ARIANNE" "ALESHIA" "YUNG" "WILLIEMAE" "TROY" "TRINH" "THORA" "TAI" "SVETLANA" "SHERIKA" "SHEMEKA" "SHAUNDA" "ROSELINE" "RICKI" "MELDA" "MALLIE" "LAVONNA" "LATINA" "LARRY" "LAQUANDA" "LALA" "LACHELLE" "KLARA" "KANDIS" "JOHNA" "JEANMARIE" "JAYE" "HANG" "GRAYCE" "GERTUDE" "EMERITA" "EBONIE" "CLORINDA" "CHING" "CHERY" "CAROLA" "BREANN" "BLOSSOM" "BERNARDINE" "BECKI" "ARLETHA" "ARGELIA" "ARA" "ALITA" "YULANDA" "YON" "YESSENIA" "TOBI" "TASIA" "SYLVIE" "SHIRL" "SHIRELY" "SHERIDAN" "SHELLA" "SHANTELLE" "SACHA" "ROYCE" "REBECKA" "REAGAN" "PROVIDENCIA" "PAULENE" "MISHA" "MIKI" "MARLINE" "MARICA" "LORITA" "LATOYIA" "LASONYA" "KERSTIN" "KENDA" "KEITHA" "KATHRIN" "JAYMIE" "JACK" "GRICELDA" "GINETTE" "ERYN" "ELINA" "ELFRIEDA" "DANYEL" "CHEREE" "CHANELLE" "BARRIE" "AVERY" "AURORE" "ANNAMARIA" "ALLEEN" "AILENE" "AIDE" "YASMINE" "VASHTI" "VALENTINE" "TREASA" "TORY" "TIFFANEY" "SHERYLL" "SHARIE" "SHANAE" "SAU" "RAISA" "PA" "NEDA" "MITSUKO" "MIRELLA" "MILDA" "MARYANNA" "MARAGRET" "MABELLE" "LUETTA" "LORINA" "LETISHA" "LATARSHA" "LANELLE" "LAJUANA" "KRISSY" "KARLY" "KARENA" "JON" "JESSIKA" "JERICA" "JEANELLE" "JANUARY" "JALISA" "JACELYN" "IZOLA" "IVEY" "GREGORY" "EUNA" "ETHA" "DREW" "DOMITILA" "DOMINICA" "DAINA" "CREOLA" "CARLI" "CAMIE" "BUNNY" "BRITTNY" "ASHANTI" "ANISHA" "ALEEN" "ADAH" "YASUKO" "WINTER" "VIKI" "VALRIE" "TONA" "TINISHA" "THI" "TERISA" "TATUM" "TANEKA" "SIMONNE" "SHALANDA" "SERITA" "RESSIE" "REFUGIA" "PAZ" "OLENE" "NA" "MERRILL" "MARGHERITA" "MANDIE" "MAN" "MAIRE" "LYNDIA" "LUCI" "LORRIANE" "LORETA" "LEONIA" "LAVONA" "LASHAWNDA" "LAKIA" "KYOKO" "KRYSTINA" "KRYSTEN" "KENIA" "KELSI" "JUDE" "JEANICE" "ISOBEL" "GEORGIANN" "GENNY" "FELICIDAD" "EILENE" "DEON" "DELOISE" "DEEDEE" "DANNIE" "CONCEPTION" "CLORA" "CHERILYN" "CHANG" "CALANDRA" "BERRY" "ARMANDINA" "ANISA" "ULA" "TIMOTHY" "TIERA" "THERESSA" "STEPHANIA" "SIMA" "SHYLA" "SHONTA" "SHERA" "SHAQUITA" "SHALA" "SAMMY" "ROSSANA" "NOHEMI" "NERY" "MORIAH" "MELITA" "MELIDA" "MELANI" "MARYLYNN" "MARISHA" "MARIETTE" "MALORIE" "MADELENE" "LUDIVINA" "LORIA" "LORETTE" "LORALEE" "LIANNE" "LEON" "LAVENIA" "LAURINDA" "LASHON" "KIT" "KIMI" "KEILA" "KATELYNN" "KAI" "JONE" "JOANE" "JI" "JAYNA" "JANELLA" "JA" "HUE" "HERTHA" "FRANCENE" "ELINORE" "DESPINA" "DELSIE" "DEEDRA" "CLEMENCIA" "CARRY" "CAROLIN" "CARLOS" "BULAH" "BRITTANIE" "BOK" "BLONDELL" "BIBI" "BEAULAH" "BEATA" "ANNITA" "AGRIPINA" "VIRGEN" "VALENE" "UN" "TWANDA" "TOMMYE" "TOI" "TARRA" "TARI" "TAMMERA" "SHAKIA" "SADYE" "RUTHANNE" "ROCHEL" "RIVKA" "PURA" "NENITA" "NATISHA" "MING" "MERRILEE" "MELODEE" "MARVIS" "LUCILLA" "LEENA" "LAVETA" "LARITA" "LANIE" "KEREN" "ILEEN" "GEORGEANN" "GENNA" "GENESIS" "FRIDA" "EWA" "EUFEMIA" "EMELY" "ELA" "EDYTH" "DEONNA" "DEADRA" "DARLENA" "CHANELL" "CHAN" "CATHERN" "CASSONDRA" "CASSAUNDRA" "BERNARDA" "BERNA" "ARLINDA" "ANAMARIA" "ALBERT" "WESLEY" "VERTIE" "VALERI" "TORRI" "TATYANA" "STASIA" "SHERISE" "SHERILL" "SEASON" "SCOTTIE" "SANDA" "RUTHE" "ROSY" "ROBERTO" "ROBBI" "RANEE" "QUYEN" "PEARLY" "PALMIRA" "ONITA" "NISHA" "NIESHA" "NIDA" "NEVADA" "NAM" "MERLYN" "MAYOLA" "MARYLOUISE" "MARYLAND" "MARX" "MARTH" "MARGENE" "MADELAINE" "LONDA" "LEONTINE" "LEOMA" "LEIA" "LAWRENCE" "LAURALEE" "LANORA" "LAKITA" "KIYOKO" "KETURAH" "KATELIN" "KAREEN" "JONIE" "JOHNETTE" "JENEE" "JEANETT" "IZETTA" "HIEDI" "HEIKE" "HASSIE" "HAROLD" "GIUSEPPINA" "GEORGANN" "FIDELA" "FERNANDE" "ELWANDA" "ELLAMAE" "ELIZ" "DUSTI" "DOTTY" "CYNDY" "CORALIE" "CELESTA" "ARGENTINA" "ALVERTA" "XENIA" "WAVA" "VANETTA" "TORRIE" "TASHINA" "TANDY" "TAMBRA" "TAMA" "STEPANIE" "SHILA" "SHAUNTA" "SHARAN" "SHANIQUA" "SHAE" "SETSUKO" "SERAFINA" "SANDEE" "ROSAMARIA" "PRISCILA" "OLINDA" "NADENE" "MUOI" "MICHELINA" "MERCEDEZ" "MARYROSE" "MARIN" "MARCENE" "MAO" "MAGALI" "MAFALDA" "LOGAN" "LINN" "LANNIE" "KAYCE" "KAROLINE" "KAMILAH" "KAMALA" "JUSTA" "JOLINE" "JENNINE" "JACQUETTA" "IRAIDA" "GERALD" "GEORGEANNA" "FRANCHESCA" "FAIRY" "EMELINE" "ELANE" "EHTEL" "EARLIE" "DULCIE" "DALENE" "CRIS" "CLASSIE" "CHERE" "CHARIS" "CAROYLN" "CARMINA" "CARITA" "BRIAN" "BETHANIE" "AYAKO" "ARICA" "AN" "ALYSA" "ALESSANDRA" "AKILAH" "ADRIEN" "ZETTA" "YOULANDA" "YELENA" "YAHAIRA" "XUAN" "WENDOLYN" "VICTOR" "TIJUANA" "TERRELL" "TERINA" "TERESIA" "SUZI" "SUNDAY" "SHERELL" "SHAVONDA" "SHAUNTE" "SHARDA" "SHAKITA" "SENA" "RYANN" "RUBI" "RIVA" "REGINIA" "REA" "RACHAL" "PARTHENIA" "PAMULA" "MONNIE" "MONET" "MICHAELE" "MELIA" "MARINE" "MALKA" "MAISHA" "LISANDRA" "LEO" "LEKISHA" "LEAN" "LAURENCE" "LAKENDRA" "KRYSTIN" "KORTNEY" "KIZZIE" "KITTIE" "KERA" "KENDAL" "KEMBERLY" "KANISHA" "JULENE" "JULE" "JOSHUA" "JOHANNE" "JEFFREY" "JAMEE" "HAN" "HALLEY" "GIDGET" "GALINA" "FREDRICKA" "FLETA" "FATIMAH" "EUSEBIA" "ELZA" "ELEONORE" "DORTHEY" "DORIA" "DONELLA" "DINORAH" "DELORSE" "CLARETHA" "CHRISTINIA" "CHARLYN" "BONG" "BELKIS" "AZZIE" "ANDERA" "AIKO" "ADENA" "YER" "YAJAIRA" "WAN" "VANIA" "ULRIKE" "TOSHIA" "TIFANY" "STEFANY" "SHIZUE" "SHENIKA" "SHAWANNA" "SHAROLYN" "SHARILYN" "SHAQUANA" "SHANTAY" "SEE" "ROZANNE" "ROSELEE" "RICKIE" "REMONA" "REANNA" "RAELENE" "QUINN" "PHUNG" "PETRONILA" "NATACHA" "NANCEY" "MYRL" "MIYOKO" "MIESHA" "MERIDETH" "MARVELLA" "MARQUITTA" "MARHTA" "MARCHELLE" "LIZETH" "LIBBIE" "LAHOMA" "LADAWN" "KINA" "KATHELEEN" "KATHARYN" "KARISA" "KALEIGH" "JUNIE" "JULIEANN" "JOHNSIE" "JANEAN" "JAIMEE" "JACKQUELINE" "HISAKO" "HERMA" "HELAINE" "GWYNETH" "GLENN" "GITA" "EUSTOLIA" "EMELINA" "ELIN" "EDRIS" "DONNETTE" "DONNETTA" "DIERDRE" "DENAE" "DARCEL" "CLAUDE" "CLARISA" "CINDERELLA" "CHIA" "CHARLESETTA" "CHARITA" "CELSA" "CASSY" "CASSI" "CARLEE" "BRUNA" "BRITTANEY" "BRANDE" "BILLI" "BAO" "ANTONETTA" "ANGLA" "ANGELYN" "ANALISA" "ALANE" "WENONA" "WENDIE" "VERONIQUE" "VANNESA" "TOBIE" "TEMPIE" "SUMIKO" "SULEMA" "SPARKLE" "SOMER" "SHEBA" "SHAYNE" "SHARICE" "SHANEL" "SHALON" "SAGE" "ROY" "ROSIO" "ROSELIA" "RENAY" "REMA" "REENA" "PORSCHE" "PING" "PEG" "OZIE" "ORETHA" "ORALEE" "ODA" "NU" "NGAN" "NAKESHA" "MILLY" "MARYBELLE" "MARLIN" "MARIS" "MARGRETT" "MARAGARET" "MANIE" "LURLENE" "LILLIA" "LIESELOTTE" "LAVELLE" "LASHAUNDA" "LAKEESHA" "KEITH" "KAYCEE" "KALYN" "JOYA" "JOETTE" "JENAE" "JANIECE" "ILLA" "GRISEL" "GLAYDS" "GENEVIE" "GALA" "FREDDA" "FRED" "ELMER" "ELEONOR" "DEBERA" "DEANDREA" "DAN" "CORRINNE" "CORDIA" "CONTESSA" "COLENE" "CLEOTILDE" "CHARLOTT" "CHANTAY" "CECILLE" "BEATRIS" "AZALEE" "ARLEAN" "ARDATH" "ANJELICA" "ANJA" "ALFREDIA" "ALEISHA" "ADAM" "ZADA" "YUONNE" "XIAO" "WILLODEAN" "WHITLEY" "VENNIE" "VANNA" "TYISHA" "TOVA" "TORIE" "TONISHA" "TILDA" "TIEN" "TEMPLE" "SIRENA" "SHERRIL" "SHANTI" "SHAN" "SENAIDA" "SAMELLA" "ROBBYN" "RENDA" "REITA" "PHEBE" "PAULITA" "NOBUKO" "NGUYET" "NEOMI" "MOON" "MIKAELA" "MELANIA" "MAXIMINA" "MARG" "MAISIE" "LYNNA" "LILLI" "LAYNE" "LASHAUN" "LAKENYA" "LAEL" "KIRSTIE" "KATHLINE" "KASHA" "KARLYN" "KARIMA" "JOVAN" "JOSEFINE" "JENNELL" "JACQUI" "JACKELYN" "HYO" "HIEN" "GRAZYNA" "FLORRIE" "FLORIA" "ELEONORA" "DWANA" "DORLA" "DONG" "DELMY" "DEJA" "DEDE" "DANN" "CRYSTA" "CLELIA" "CLARIS" "CLARENCE" "CHIEKO" "CHERLYN" "CHERELLE" "CHARMAIN" "CHARA" "CAMMY" "BEE" "ARNETTE" "ARDELLE" "ANNIKA" "AMIEE" "AMEE" "ALLENA" "YVONE" "YUKI" "YOSHIE" "YEVETTE" "YAEL" "WILLETTA" "VONCILE" "VENETTA" "TULA" "TONETTE" "TIMIKA" "TEMIKA" "TELMA" "TEISHA" "TAREN" "TA" "STACEE" "SHIN" "SHAWNTA" "SATURNINA" "RICARDA" "POK" "PASTY" "ONIE" "NUBIA" "MORA" "MIKE" "MARIELLE" "MARIELLA" "MARIANELA" "MARDELL" "MANY" "LUANNA" "LOISE" "LISABETH" "LINDSY" "LILLIANA" "LILLIAM" "LELAH" "LEIGHA" "LEANORA" "LANG" "KRISTEEN" "KHALILAH" "KEELEY" "KANDRA" "JUNKO" "JOAQUINA" "JERLENE" "JANI" "JAMIKA" "JAME" "HSIU" "HERMILA" "GOLDEN" "GENEVIVE" "EVIA" "EUGENA" "EMMALINE" "ELFREDA" "ELENE" "DONETTE" "DELCIE" "DEEANNA" "DARCEY" "CUC" "CLARINDA" "CIRA" "CHAE" "CELINDA" "CATHERYN" "CATHERIN" "CASIMIRA" "CARMELIA" "CAMELLIA" "BREANA" "BOBETTE" "BERNARDINA" "BEBE" "BASILIA" "ARLYNE" "AMAL" "ALAYNA" "ZONIA" "ZENIA" "YURIKO" "YAEKO" "WYNELL" "WILLOW" "WILLENA" "VERNIA" "TU" "TRAVIS" "TORA" "TERRILYN" "TERICA" "TENESHA" "TAWNA" "TAJUANA" "TAINA" "STEPHNIE" "SONA" "SOL" "SINA" "SHONDRA" "SHIZUKO" "SHERLENE" "SHERICE" "SHARIKA" "ROSSIE" "ROSENA" "RORY" "RIMA" "RIA" "RHEBA" "RENNA" "PETER" "NATALYA" "NANCEE" "MELODI" "MEDA" "MAXIMA" "MATHA" "MARKETTA" "MARICRUZ" "MARCELENE" "MALVINA" "LUBA" "LOUETTA" "LEIDA" "LECIA" "LAURAN" "LASHAWNA" "LAINE" "KHADIJAH" "KATERINE" "KASI" "KALLIE" "JULIETTA" "JESUSITA" "JESTINE" "JESSIA" "JEREMY" "JEFFIE" "JANYCE" "ISADORA" "GEORGIANNE" "FIDELIA" "EVITA" "EURA" "EULAH" "ESTEFANA" "ELSY" "ELIZABET" "ELADIA" "DODIE" "DION" "DIA" "DENISSE" "DELORAS" "DELILA" "DAYSI" "DAKOTA" "CURTIS" "CRYSTLE" "CONCHA" "COLBY" "CLARETTA" "CHU" "CHRISTIA" "CHARLSIE" "CHARLENA" "CARYLON" "BETTYANN" "ASLEY" "ASHLEA" "AMIRA" "AI" "AGUEDA" "AGNUS" "YUETTE" "VINITA" "VICTORINA" "TYNISHA" "TREENA" "TOCCARA" "TISH" "THOMASENA" "TEGAN" "SOILA" "SHILOH" "SHENNA" "SHARMAINE" "SHANTAE" "SHANDI" "SEPTEMBER" "SARAN" "SARAI" "SANA" "SAMUEL" "SALLEY" "ROSETTE" "ROLANDE" "REGINE" "OTELIA" "OSCAR" "OLEVIA" "NICHOLLE" "NECOLE" "NAIDA" "MYRTA" "MYESHA" "MITSUE" "MINTA" "MERTIE" "MARGY" "MAHALIA" "MADALENE" "LOVE" "LOURA" "LOREAN" "LEWIS" "LESHA" "LEONIDA" "LENITA" "LAVONE" "LASHELL" "LASHANDRA" "LAMONICA" "KIMBRA" "KATHERINA" "KARRY" "KANESHA" "JULIO" "JONG" "JENEVA" "JAQUELYN" "HWA" "GILMA" "GHISLAINE" "GERTRUDIS" "FRANSISCA" "FERMINA" "ETTIE" "ETSUKO" "ELLIS" "ELLAN" "ELIDIA" "EDRA" "DORETHEA" "DOREATHA" "DENYSE" "DENNY" "DEETTA" "DAINE" "CYRSTAL" "CORRIN" "CAYLA" "CARLITA" "CAMILA" "BURMA" "BULA" "BUENA" "BLAKE" "BARABARA" "AVRIL" "AUSTIN" "ALAINE" "ZANA" "WILHEMINA" "WANETTA" "VIRGIL" "VI" "VERONIKA" "VERNON" "VERLINE" "VASILIKI" "TONITA" "TISA" "TEOFILA" "TAYNA" "TAUNYA" "TANDRA" "TAKAKO" "SUNNI" "SUANNE" "SIXTA" "SHARELL" "SEEMA" "RUSSELL" "ROSENDA" "ROBENA" "RAYMONDE" "PEI" "PAMILA" "OZELL" "NEIDA" "NEELY" "MISTIE" "MICHA" "MERISSA" "MAURITA" "MARYLN" "MARYETTA" "MARSHALL" "MARCELL" "MALENA" "MAKEDA" "MADDIE" "LOVETTA" "LOURIE" "LORRINE" "LORILEE" "LESTER" "LAURENA" "LASHAY" "LARRAINE" "LAREE" "LACRESHA" "KRISTLE" "KRISHNA" "KEVA" "KEIRA" "KAROLE" "JOIE" "JINNY" "JEANNETTA" "JAMA" "HEIDY" "GILBERTE" "GEMA" "FAVIOLA" "EVELYNN" "ENDA" "ELLI" "ELLENA" "DIVINA" "DAGNY" "COLLENE" "CODI" "CINDIE" "CHASSIDY" "CHASIDY" "CATRICE" "CATHERINA" "CASSEY" "CAROLL" "CARLENA" "CANDRA" "CALISTA" "BRYANNA" "BRITTENY" "BEULA" "BARI" "AUDRIE" "AUDRIA" "ARDELIA" "ANNELLE" "ANGILA" "ALONA" "ALLYN" "DOUGLAS" "ROGER" "JONATHAN" "RALPH" "NICHOLAS" "BENJAMIN" "BRUCE" "HARRY" "WAYNE" "STEVE" "HOWARD" "ERNEST" "PHILLIP" "TODD" "CRAIG" "ALAN" "PHILIP" "EARL" "DANNY" "BRYAN" "STANLEY" "LEONARD" "NATHAN" "MANUEL" "RODNEY" "MARVIN" "VINCENT" "JEFFERY" "JEFF" "CHAD" "JACOB" "ALFRED" "BRADLEY" "HERBERT" "FREDERICK" "EDWIN" "DON" "RICKY" "RANDALL" "BARRY" "BERNARD" "LEROY" "MARCUS" "THEODORE" "CLIFFORD" "MIGUEL" "JIM" "TOM" "CALVIN" "BILL" "LLOYD" "DEREK" "WARREN" "DARRELL" "JEROME" "FLOYD" "ALVIN" "TIM" "GORDON" "GREG" "JORGE" "DUSTIN" "PEDRO" "DERRICK" "ZACHARY" "HERMAN" "GLEN" "HECTOR" "RICARDO" "RICK" "BRENT" "RAMON" "GILBERT" "MARC" "REGINALD" "RUBEN" "NATHANIEL" "RAFAEL" "EDGAR" "MILTON" "RAUL" "BEN" "CHESTER" "DUANE" "FRANKLIN" "BRAD" "RON" "ROLAND" "ARNOLD" "HARVEY" "JARED" "ERIK" "DARRYL" "NEIL" "JAVIER" "FERNANDO" "CLINTON" "TED" "MATHEW" "TYRONE" "DARREN" "LANCE" "KURT" "ALLAN" "NELSON" "GUY" "CLAYTON" "HUGH" "MAX" "DWAYNE" "DWIGHT" "ARMANDO" "FELIX" "EVERETT" "IAN" "WALLACE" "KEN" "BOB" "ALFREDO" "ALBERTO" "DAVE" "IVAN" "BYRON" "ISAAC" "MORRIS" "CLIFTON" "WILLARD" "ROSS" "ANDY" "SALVADOR" "KIRK" "SERGIO" "SETH" "KENT" "TERRANCE" "EDUARDO" "TERRENCE" "ENRIQUE" "WADE" "STUART" "FREDRICK" "ARTURO" "ALEJANDRO" "NICK" "LUTHER" "WENDELL" "JEREMIAH" "JULIUS" "OTIS" "TREVOR" "OLIVER" "LUKE" "HOMER" "GERARD" "DOUG" "KENNY" "HUBERT" "LYLE" "MATT" "ALFONSO" "ORLANDO" "REX" "CARLTON" "ERNESTO" "NEAL" "PABLO" "LORENZO" "OMAR" "WILBUR" "GRANT" "HORACE" "RODERICK" "ABRAHAM" "WILLIS" "RICKEY" "ANDRES" "CESAR" "JOHNATHAN" "MALCOLM" "RUDOLPH" "DAMON" "KELVIN" "PRESTON" "ALTON" "ARCHIE" "MARCO" "WM" "PETE" "RANDOLPH" "GARRY" "GEOFFREY" "JONATHON" "FELIPE" "GERARDO" "ED" "DOMINIC" "DELBERT" "COLIN" "GUILLERMO" "EARNEST" "LUCAS" "BENNY" "SPENCER" "RODOLFO" "MYRON" "EDMUND" "GARRETT" "SALVATORE" "CEDRIC" "LOWELL" "GREGG" "SHERMAN" "WILSON" "SYLVESTER" "ROOSEVELT" "ISRAEL" "JERMAINE" "FORREST" "WILBERT" "LELAND" "SIMON" "CLARK" "IRVING" "BRYANT" "OWEN" "RUFUS" "WOODROW" "KRISTOPHER" "MACK" "LEVI" "MARCOS" "GUSTAVO" "JAKE" "LIONEL" "GILBERTO" "CLINT" "NICOLAS" "ISMAEL" "ORVILLE" "ERVIN" "DEWEY" "AL" "WILFRED" "JOSH" "HUGO" "IGNACIO" "CALEB" "TOMAS" "SHELDON" "ERICK" "STEWART" "DOYLE" "DARREL" "ROGELIO" "TERENCE" "SANTIAGO" "ALONZO" "ELIAS" "BERT" "ELBERT" "RAMIRO" "CONRAD" "NOAH" "GRADY" "PHIL" "CORNELIUS" "LAMAR" "ROLANDO" "CLAY" "PERCY" "DEXTER" "BRADFORD" "DARIN" "AMOS" "MOSES" "IRVIN" "SAUL" "ROMAN" "RANDAL" "TIMMY" "DARRIN" "WINSTON" "BRENDAN" "ABEL" "DOMINICK" "BOYD" "EMILIO" "ELIJAH" "DOMINGO" "EMMETT" "MARLON" "EMANUEL" "JERALD" "EDMOND" "EMIL" "DEWAYNE" "WILL" "OTTO" "TEDDY" "REYNALDO" "BRET" "JESS" "TRENT" "HUMBERTO" "EMMANUEL" "STEPHAN" "VICENTE" "LAMONT" "GARLAND" "MILES" "EFRAIN" "HEATH" "RODGER" "HARLEY" "ETHAN" "ELDON" "ROCKY" "PIERRE" "JUNIOR" "FREDDY" "ELI" "BRYCE" "ANTOINE" "STERLING" "CHASE" "GROVER" "ELTON" "CLEVELAND" "DYLAN" "CHUCK" "DAMIAN" "REUBEN" "STAN" "AUGUST" "LEONARDO" "JASPER" "RUSSEL" "ERWIN" "BENITO" "HANS" "MONTE" "BLAINE" "ERNIE" "CURT" "QUENTIN" "AGUSTIN" "MURRAY" "JAMAL" "ADOLFO" "HARRISON" "TYSON" "BURTON" "BRADY" "ELLIOTT" "WILFREDO" "BART" "JARROD" "VANCE" "DENIS" "DAMIEN" "JOAQUIN" "HARLAN" "DESMOND" "ELLIOT" "DARWIN" "GREGORIO" "BUDDY" "XAVIER" "KERMIT" "ROSCOE" "ESTEBAN" "ANTON" "SOLOMON" "SCOTTY" "NORBERT" "ELVIN" "WILLIAMS" "NOLAN" "ROD" "QUINTON" "HAL" "BRAIN" "ROB" "ELWOOD" "KENDRICK" "DARIUS" "MOISES" "FIDEL" "THADDEUS" "CLIFF" "MARCEL" "JACKSON" "RAPHAEL" "BRYON" "ARMAND" "ALVARO" "JEFFRY" "DANE" "JOESPH" "THURMAN" "NED" "RUSTY" "MONTY" "FABIAN" "REGGIE" "MASON" "GRAHAM" "ISAIAH" "VAUGHN" "GUS" "LOYD" "DIEGO" "ADOLPH" "NORRIS" "MILLARD" "ROCCO" "GONZALO" "DERICK" "RODRIGO" "WILEY" "RIGOBERTO" "ALPHONSO" "TY" "NOE" "VERN" "REED" "JEFFERSON" "ELVIS" "BERNARDO" "MAURICIO" "HIRAM" "DONOVAN" "BASIL" "RILEY" "NICKOLAS" "MAYNARD" "SCOT" "VINCE" "QUINCY" "EDDY" "SEBASTIAN" "FEDERICO" "ULYSSES" "HERIBERTO" "DONNELL" "COLE" "DAVIS" "GAVIN" "EMERY" "WARD" "ROMEO" "JAYSON" "DANTE" "CLEMENT" "COY" "MAXWELL" "JARVIS" "BRUNO" "ISSAC" "DUDLEY" "BROCK" "SANFORD" "CARMELO" "BARNEY" "NESTOR" "STEFAN" "DONNY" "ART" "LINWOOD" "BEAU" "WELDON" "GALEN" "ISIDRO" "TRUMAN" "DELMAR" "JOHNATHON" "SILAS" "FREDERIC" "DICK" "IRWIN" "MERLIN" "CHARLEY" "MARCELINO" "HARRIS" "CARLO" "TRENTON" "KURTIS" "HUNTER" "AURELIO" "WINFRED" "VITO" "COLLIN" "DENVER" "CARTER" "LEONEL" "EMORY" "PASQUALE" "MOHAMMAD" "MARIANO" "DANIAL" "LANDON" "DIRK" "BRANDEN" "ADAN" "BUFORD" "GERMAN" "WILMER" "EMERSON" "ZACHERY" "FLETCHER" "JACQUES" "ERROL" "DALTON" "MONROE" "JOSUE" "EDWARDO" "BOOKER" "WILFORD" "SONNY" "SHELTON" "CARSON" "THERON" "RAYMUNDO" "DAREN" "HOUSTON" "ROBBY" "LINCOLN" "GENARO" "BENNETT" "OCTAVIO" "CORNELL" "HUNG" "ARRON" "ANTONY" "HERSCHEL" "GIOVANNI" "GARTH" "CYRUS" "CYRIL" "RONNY" "LON" "FREEMAN" "DUNCAN" "KENNITH" "CARMINE" "ERICH" "CHADWICK" "WILBURN" "RUSS" "REID" "MYLES" "ANDERSON" "MORTON" "JONAS" "FOREST" "MITCHEL" "MERVIN" "ZANE" "RICH" "JAMEL" "LAZARO" "ALPHONSE" "RANDELL" "MAJOR" "JARRETT" "BROOKS" "ABDUL" "LUCIANO" "SEYMOUR" "EUGENIO" "MOHAMMED" "VALENTIN" "CHANCE" "ARNULFO" "LUCIEN" "FERDINAND" "THAD" "EZRA" "ALDO" "RUBIN" "ROYAL" "MITCH" "EARLE" "ABE" "WYATT" "MARQUIS" "LANNY" "KAREEM" "JAMAR" "BORIS" "ISIAH" "EMILE" "ELMO" "ARON" "LEOPOLDO" "EVERETTE" "JOSEF" "ELOY" "RODRICK" "REINALDO" "LUCIO" "JERROD" "WESTON" "HERSHEL" "BARTON" "PARKER" "LEMUEL" "BURT" "JULES" "GIL" "ELISEO" "AHMAD" "NIGEL" "EFREN" "ANTWAN" "ALDEN" "MARGARITO" "COLEMAN" "DINO" "OSVALDO" "LES" "DEANDRE" "NORMAND" "KIETH" "TREY" "NORBERTO" "NAPOLEON" "JEROLD" "FRITZ" "ROSENDO" "MILFORD" "CHRISTOPER" "ALFONZO" "LYMAN" "JOSIAH" "BRANT" "WILTON" "RICO" "JAMAAL" "DEWITT" "BRENTON" "OLIN" "FOSTER" "FAUSTINO" "CLAUDIO" "JUDSON" "GINO" "EDGARDO" "ALEC" "TANNER" "JARRED" "DONN" "TAD" "PRINCE" "PORFIRIO" "ODIS" "LENARD" "CHAUNCEY" "TOD" "MEL" "MARCELO" "KORY" "AUGUSTUS" "KEVEN" "HILARIO" "BUD" "SAL" "ORVAL" "MAURO" "ZACHARIAH" "OLEN" "ANIBAL" "MILO" "JED" "DILLON" "AMADO" "NEWTON" "LENNY" "RICHIE" "HORACIO" "BRICE" "MOHAMED" "DELMER" "DARIO" "REYES" "MAC" "JONAH" "JERROLD" "ROBT" "HANK" "RUPERT" "ROLLAND" "KENTON" "DAMION" "ANTONE" "WALDO" "FREDRIC" "BRADLY" "KIP" "BURL" "WALKER" "TYREE" "JEFFEREY" "AHMED" "WILLY" "STANFORD" "OREN" "NOBLE" "MOSHE" "MIKEL" "ENOCH" "BRENDON" "QUINTIN" "JAMISON" "FLORENCIO" "DARRICK" "TOBIAS" "HASSAN" "GIUSEPPE" "DEMARCUS" "CLETUS" "TYRELL" "LYNDON" "KEENAN" "WERNER" "GERALDO" "COLUMBUS" "CHET" "BERTRAM" "MARKUS" "HUEY" "HILTON" "DWAIN" "DONTE" "TYRON" "OMER" "ISAIAS" "HIPOLITO" "FERMIN" "ADALBERTO" "BO" "BARRETT" "TEODORO" "MCKINLEY" "MAXIMO" "GARFIELD" "RALEIGH" "LAWERENCE" "ABRAM" "RASHAD" "KING" "EMMITT" "DARON" "SAMUAL" "MIQUEL" "EUSEBIO" "DOMENIC" "DARRON" "BUSTER" "WILBER" "RENATO" "JC" "HOYT" "HAYWOOD" "EZEKIEL" "CHAS" "FLORENTINO" "ELROY" "CLEMENTE" "ARDEN" "NEVILLE" "EDISON" "DESHAWN" "NATHANIAL" "JORDON" "DANILO" "CLAUD" "SHERWOOD" "RAYMON" "RAYFORD" "CRISTOBAL" "AMBROSE" "TITUS" "HYMAN" "FELTON" "EZEQUIEL" "ERASMO" "STANTON" "LONNY" "LEN" "IKE" "MILAN" "LINO" "JAROD" "HERB" "ANDREAS" "WALTON" "RHETT" "PALMER" "DOUGLASS" "CORDELL" "OSWALDO" "ELLSWORTH" "VIRGILIO" "TONEY" "NATHANAEL" "DEL" "BENEDICT" "MOSE" "JOHNSON" "ISREAL" "GARRET" "FAUSTO" "ASA" "ARLEN" "ZACK" "WARNER" "MODESTO" "FRANCESCO" "MANUAL" "GAYLORD" "GASTON" "FILIBERTO" "DEANGELO" "MICHALE" "GRANVILLE" "WES" "MALIK" "ZACKARY" "TUAN" "ELDRIDGE" "CRISTOPHER" "CORTEZ" "ANTIONE" "MALCOM" "LONG" "KOREY" "JOSPEH" "COLTON" "WAYLON" "VON" "HOSEA" "SHAD" "SANTO" "RUDOLF" "ROLF" "REY" "RENALDO" "MARCELLUS" "LUCIUS" "KRISTOFER" "BOYCE" "BENTON" "HAYDEN" "HARLAND" "ARNOLDO" "RUEBEN" "LEANDRO" "KRAIG" "JERRELL" "JEROMY" "HOBERT" "CEDRICK" "ARLIE" "WINFORD" "WALLY" "LUIGI" "KENETH" "JACINTO" "GRAIG" "FRANKLYN" "EDMUNDO" "SID" "PORTER" "LEIF" "JERAMY" "BUCK" "WILLIAN" "VINCENZO" "SHON" "LYNWOOD" "JERE" "HAI" "ELDEN" "DORSEY" "DARELL" "BRODERICK" "ALONSO"))
(define letter-score
  '(("A" 1) ("B" 2) ("C" 3) ("D" 4) ("E" 5) ("F" 6) ("G" 7) ("H" 8) ("I" 9)
            ("J" 10) ("K" 11) ("L" 12) ("M" 13) ("N" 14) ("O" 15) ("P" 16)
            ("Q" 17) ("R" 18) ("S" 19) ("T" 20) ("U" 21) ("V" 22) ("W" 23)
            ("X" 24) ("Y" 25) ("Z" 26)))


;; (name-score name) produces the sum of all the letter scores of the name.
;; name-score: Str -> Nat

(define (name-score name)
  (foldr + 0 (map (lambda (x) (second (assoc x letter-score))) (explode name))))

(define (sum-scores name-list)
  (local [(define (name-score/acc name-list counter sum)
            (cond [(empty? name-list) sum]
                  [else
                   (name-score/acc
                    (rest name-list) (add1 counter)
                    (+ sum (* counter (name-score (first name-list)))))]))]
    (name-score/acc (quicksort name-list string<?) 1 0)))

;(sum-scores long-name-list)


;; ==== Question 23 ========================


;; (find-abundant ceiling) finds all the abundant numbers below or equal to the
;;   ceiling.
;; find-abundant: Nat -> (listof Nat)

(define (find-abundant ceiling)
  (local [(define (find-next current)
            (cond [(> current ceiling) empty]
                  [(> (factor-sum current) current)
                   (cons current (find-next (add1 current)))]
                  [else (find-next (add1 current))]))]
    (find-next 1)))

;; All the abundant numbers below 28123
(define abundant-list (find-abundant 28123))


;; (is-sum? num ab-list) checks if the number can be written as the sum of two
;;   numbers from the ab-list.
;; is-sum?: Nat (listof Nat) -> Bool

(define (is-sum? num ab-list)
  (cond [(empty? ab-list) false]
        [(> (first ab-list) (/ num 2)) false]
        [(member? (- num (first ab-list)) ab-list) true]
        [else (is-sum? num (rest ab-list))]))


;; (check-sum num-list) produces the sum of all numbers in the list which can be
;;   represented as the sum of two abundant numbers.
;; check-sum: (listof Nat) -> Nat

(define (check-sum num-list)
  (cond [(empty? num-list) 0]
        [(is-sum? (first num-list) (filter (lambda (x) (< x (first num-list)))
                                           abundant-list))
         (+ (first num-list) (check-sum (rest num-list)))]
        [else (check-sum (rest num-list))]))


;(- (* 28123 28124 0.5) (check-sum (build-list 28123 add1)))


;; ==== Question 24 ========================


(define (find-permutation num-objects permutation)
  (cond [(zero? num-objects) empty]
        [else
         (local [(define factor (factorial (sub1 num-objects)))
                 (define index (quotient (sub1 permutation) factor))]
           (cons index
                 (find-permutation (sub1 num-objects)
                                   (- permutation (* index factor)))))]))

(define (permutation->number permutation)
  (local [(define (next-number index remaining)
            (cond [(empty? index) remaining]
                  [else
                   (local [(define next (list-ref remaining (first index)))]
                     (cons next
                           (next-number (rest index)
                                        (remove next remaining))))]))]
    (next-number permutation
                 (build-list (length permutation) identity))))

;(implode
;  (map number->string (permutation->number (find-permutation 10 1000000))))


;; ==== Question 25 ========================


;; (fib n) computes the first fibonacci number with n or more digits.
;; fib: Nat -> Nat
;; requires: n > 1

(define (fib n)
  (local [(define target (expt 10 (sub1 n)))
          (define (next counter prev prev2)
            (cond [(>= prev target) counter]
                  [else (next (add1 counter) (+ prev prev2) prev)]))]
    (next 2 1 1)))

;(fib 1000)


;; ==== Question 26 ========================


;; (sieve num-list) produces the primes in the list of natural numebrs using the
;;   Sieve of Erastothenes.
;; sieve-sum: (listof Nat) -> Nat
;; requires: num-list is a list of increasing natural numbers.

(define (sieve num-list)
  (cond [(empty? num-list) empty]
        [(= 1 (first num-list))
         (sieve (rest num-list))]
        [else
         (local [(define new (first num-list))]
           (cons new (sieve
                      (filter (lambda (x) (not (= 0 (remainder x new))))
                              (rest num-list)))))]))


;; (longest-cycle prime-list) produces the number p for which 1/p has the
;;   longest repeating cycle of decimals. This makes the assumption that 1/np
;;   where n, p are Nat has no longer cycle than the max of 1/n and 1/p.
;; longest-cycle: (listof Nat) -> Nat

(define (longest-cycle prime-list)
  (local [(define (num-cycles n int)
            (cond [(integer? (/ (sub1 (expt 10 n)) int)) n]
                  [(integer? (/ (expt 10 n) int)) 0]
                  [else (num-cycles (add1 n) int)]))
          (define (search int-list record length)
            (cond [(empty? int-list) record]
                  [else
                   (local [(define new (num-cycles 1 (first int-list)))]
                     (cond [(> new length)
                            (search (rest int-list) (first int-list) new)]
                           [else (search (rest int-list) record length)]))]))]
    (search prime-list 0 0)))

;(longest-cycle (sieve (build-list 1000 add1)))


;; ==== Question 27 ========================


;; (prime? nat) determines if the nat is a prime.
;; prime?: Nat -> Bool

(define (prime? nat)
  (local [(define prime-list
            (sieve (build-list (inexact->exact (floor (sqrt nat))) add1)))
          (define (primality nat prime-list)
            (cond [(empty? prime-list) true]
                  [(zero? (remainder nat (first prime-list))) false]
                  [else (primality nat (rest prime-list))]))]
    (primality nat prime-list)))
  

;; (find-prime-quadratic ceiling) produces the product of a and b where
;;   x^2 + ax + b produces the most consecutive positive primes starting with
;;   x=0 and incrementing upwards.
;; find-prime-quadratic: Nat -> Nat

(define (find-prime-quadratic ceiling)
  (local [(define (gen-quad a b) (lambda (n) (+ (sqr n) (* n a) b)))
          (define (num-primes quad counter)
            (cond [(< (quad counter) 0) counter]
                  [(prime? (quad counter))
                   (num-primes quad (add1 counter))]
                  [else counter]))
          (define (max-primes a b product record)
            (cond [(> b ceiling)
                   (max-primes (add1 a) (* -1 ceiling) product record)]
                  [(> a ceiling) product]
                  [(or (< ((gen-quad a b) record) 0)
                       (not (prime? ((gen-quad a b) record))))
                   (max-primes a (add1 b) product record)]
                  [else
                   (local [(define new-len (num-primes (gen-quad a b) 0))]
                     (cond [(> new-len record)
                            (max-primes a (add1 b) (* a b) new-len)]
                           [else (max-primes a (add1 b) product record)]))]))]
    (max-primes (* -1 ceiling) (* -1 ceiling) 0 0)))


;(find-prime-quadratic 999)


;; ==== Question 28 ========================


;; (spiral-list-gen size) finds the sum of the diagonals of a spiral list with
;;   size x size dimensions. Note that the highest number is size^2.
;; spiral-list-gen: Nat -> Nat

(define (spiral-list-gen size)
  (local [(define (next-num counter num-list)
            (cond [(< counter size)
                   (next-num (+ 2 counter)
                             (list* (+ (* 4 counter) (first num-list))
                                    (+ (* 3 counter) (first num-list))
                                    (+ (* 2 counter) (first num-list))
                                    (+ counter (first num-list))
                                    num-list))]
                  [else num-list]))]
    (foldr + 0 (next-num 2 '(1)))))

;(spiral-list-gen 1001)


;; ==== Question 29 ========================


(define (sorted-count-not-dupes num-list)
  (foldr (lambda (x y) (cond [(empty? y) (list x 1)]
                             [(= x (first y)) y]
                             [else (list x (add1 (second y)))]))
         empty
         num-list))


(define (gen-power-list start stop)
  (quicksort
   (foldr append empty
          (map (lambda (y) (map (lambda (x) (expt y x))
                                (build-list (+ stop (* -1 start) 1)
                                            (lambda (a) (+ a start)))))
               (build-list (+ stop (* -1 start) 1)
                           (lambda (a) (+ a start)))))
   <))

;(second (sorted-count-not-dupes (gen-power-list 2 100)))